name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  awesome_dialog: ^2.2.1
  badges: ^3.1.2
  beamer: 1.5.2
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  bootstrap_icons: ^1.5.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.4  
  dio: ^5.2.1+1
  drift: ^2.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.2
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.9 # help us to use SVG in our app
  font_awesome_flutter: ^10.1.0
  formz: ^0.4.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  google_fonts: 6.1.0
  grouped_list: ^6.0.0
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.4.0
  package_info_plus: ^4.2.0
  path: ^1.8.0
  path_provider: ^2.0.9
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.13
  sqlite3_flutter_libs: ^0.5.24
  url_launcher: ^6.0.20

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.5
  change_app_package_name: ^1.0.0
  drift_dev: ^2.0.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.1.5
  mocktail: ^1.0.3
  permission_handler: ^11.0.1
  very_good_analysis: ^5.1.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_gen:
  integrations:
    flutter_svg: true
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  ios: true
  remove_alpha_ios: true